# Document:
# http://simiki.org/docs/configuration.html

url: "http://wiki.fenghong.tech"
title: "Wiki · Louis"
keywords: 
description: 
author: "louis"
theme: yasimple_x2

#markdown Parser#
markdown:
  - fenced_code
  - extra
  - codehilite(css_class=hlcode, linenums=False)
  - toc(title=Table of Contents)
